import { NearbyMultipeer } from '@squareetlabs/capacitor-nearby-multipeer';

// Service ID for discovery (must match in AndroidManifest if generated by Android Studio, but for plugin usually dynamic)
// KEEP THIS EXTREMELY SHORT! BLE Advertising has a 31-byte limit.
// 128-bit UUID (16 bytes) + Flags (3 bytes) = 19 bytes used.
// Remaining: ~12 bytes. We are using 'G' (1) + 'F99' (3) = 4 bytes.
const SERVICE_ID = 'G';
const STRATEGY = 'P2P_CLUSTER'; // Mesh-like strategy (M-to-N)

class MeshService {
    constructor() {
        this.peers = new Map(); // endpointId -> peerInfo
        this.messages = [];
        this.connectedEndpoints = new Set();
        this.onPeersUpdated = null;
        this.onMessageReceived = null;
        this.isInitialized = false;
        // Absolute minimum name. 'F' + 2 digits.
        this.myEndpointName = `F${Math.floor(Math.random() * 90) + 10}`;
    }

    async initialize() {
        if (this.isInitialized) return;

        try {
            // Must initialize FIRST to ensure native client exists
            await NearbyMultipeer.initialize({ serviceId: SERVICE_ID });

            // THEN stop any lingering sessions cleanly
            // We catch these specifically in case they fail, but client should be ready now.
            try {
                await NearbyMultipeer.stopAdvertising();
                await NearbyMultipeer.stopDiscovery();
            } catch (e) {
                console.warn('MeshService: Cleanup warning', e);
            }

            this.isInitialized = true;
            console.log('MeshService: Initialized');
        } catch (err) {
            console.error('MeshService: Init failed', err);
            // If init failed, we can't do much.
        }

        // Listeners for Discovery
        NearbyMultipeer.addListener('endpointFound', (peer) => {
            console.log('MeshService: Peer Found', peer);
            if (this.connectedEndpoints.has(peer.endpointId)) {
                console.log('MeshService: Already connected to', peer.endpointId);
                return;
            }

            this.peers.set(peer.endpointId, { ...peer, status: 'found' });
            this._notifyPeers();

            // AUTO-CONNECT with random delay to prevent collision (A connects to B while B connects to A)
            // and to ensure stack is ready.
            const delay = Math.floor(Math.random() * 2000) + 1000; // 1-3 seconds delay
            console.log(`MeshService: Queuing auto-connect to ${peer.endpointId} in ${delay}ms`);

            setTimeout(() => {
                // Double check status before connecting
                if (!this.connectedEndpoints.has(peer.endpointId)) {
                    this.connect(peer.endpointId);
                }
            }, delay);
        });

        NearbyMultipeer.addListener('endpointLost', (peer) => {
            console.log('MeshService: Peer Lost', peer);
            this.peers.delete(peer.endpointId);
            this.connectedEndpoints.delete(peer.endpointId);
            this._notifyPeers();

            // If we lost everyone, restart discovery to find them again
            if (this.connectedEndpoints.size === 0) {
                console.log('MeshService: Lost all peers, restarting discovery...');
                this.startDiscovery();
            }
        });

        // Listeners for Connection
        NearbyMultipeer.addListener('connectionRequested', async (interaction) => {
            console.log('MeshService: Connection Requested', interaction);
            // Auto-accept
            try {
                await NearbyMultipeer.acceptConnection({ endpointId: interaction.endpointId });
                console.log('MeshService: Auto-accepted connection from', interaction.endpointId);
            } catch (err) {
                console.error('MeshService: Accept failed', err);
            }
        });

        NearbyMultipeer.addListener('connectionResult', (result) => {
            console.log('MeshService: Connection Result', result);
            // result: { endpointId, status: 0 (success) | -1 (error) } - Check definition, might be number or string depending on plugin version
            // Definition says: status: number. 0 = success.
            if (result.status === 0 || result.status === 'CONNECTED') { // Handling both just in case
                const peer = this.peers.get(result.endpointId);
                if (peer) {
                    peer.status = 'connected';
                    this.peers.set(result.endpointId, peer);
                }
                this.connectedEndpoints.add(result.endpointId);
                this._notifyPeers();

                // STABILITY FIX: Stop discovery once connected to save bandwidth/radio
                // We keep advertising so others can find us, but we stop looking actively.
                console.log('MeshService: Connected! Stopping discovery to stabilize connection.');
                NearbyMultipeer.stopDiscovery();

                // Start Heartbeat if not running
                this._startHeartbeat();

            } else {
                this.connectedEndpoints.delete(result.endpointId);
                console.log('MeshService: Connection failed, restarting discovery');
                this.startDiscovery();
            }
        });

        NearbyMultipeer.addListener('endpointLost', (data) => { // Duplicate handler for disconnection? Definition has endpointLost.
            // Wait, definitions have 'endpointLost' but no 'onDisconnected'. 
            // Likely 'endpointLost' covers it, or there is no specific disconnected event other than lost.
            // Let's stick to standard events.
        });

        // Listeners for Payload (Messages)
        NearbyMultipeer.addListener('message', (payload) => {
            console.log('MeshService: Message Received', payload);
            if (payload.data) {
                try {
                    const rawText = atob(payload.data);
                    const text = rawText.trim(); // TRIM to ensure no whitespace issues

                    // Filter out heartbeats
                    if (text === 'HEARTBEAT') {
                        console.log('MeshService: Heartbeat from', payload.endpointId);
                        return;
                    }

                    // Check for JSON (System Messages like SOS)
                    if (text.startsWith('{') && text.includes('SOS_ALERT')) {
                        try {
                            const data = JSON.parse(text);
                            if (data.type === 'SOS_ALERT') {
                                console.log('MeshService: SOS RECEIVED!', data.payload);
                                // Trigger global alert
                                this._handleSystemAlert(data.payload);
                                // Also show in chat
                                this._handleIncomingMessage(payload.endpointId, `🚨 SOS ALERT 🚨\nFrom: ${data.payload.boatNumber}\nLat: ${data.payload.location.lat}\nLng: ${data.payload.location.lng}`);
                                return;
                            }
                        } catch (e) {
                            console.warn('MeshService: Failed to parse potential JSON', e);
                        }
                    }

                    this._handleIncomingMessage(payload.endpointId, text);
                } catch (e) {
                    // Maybe it's raw text?
                    console.error('MeshService: Decode failed', e);
                    this._handleIncomingMessage(payload.endpointId, payload.data);
                }
            }
        });
    }

    _handleSystemAlert(sos) {
        // Trigger a custom event that the UI can listen to
        const event = new CustomEvent('cg_sos_received', { detail: sos });
        window.dispatchEvent(event);

        // Browser Notification (if supported/granted)
        if ("Notification" in window && Notification.permission === "granted") {
            new Notification(`SOS: ${sos.boatNumber}`, { body: `Emergency detected at ${sos.location.lat}, ${sos.location.lng}` });
        }
    }

    _startHeartbeat() {
        if (this.heartbeatInterval) return;
        console.log('MeshService: Starting Heartbeat');
        this.heartbeatInterval = setInterval(() => {
            if (this.connectedEndpoints.size > 0) {
                this.sendMessage('HEARTBEAT').catch(e => console.warn('Heartbeat failed', e));
            } else {
                this._stopHeartbeat();
            }
        }, 5000); // 5 seconds
    }

    _stopHeartbeat() {
        if (this.heartbeatInterval) {
            clearInterval(this.heartbeatInterval);
            this.heartbeatInterval = null;
            console.log('MeshService: Stopped Heartbeat');
        }
    }

    async startAdvertising() {
        try {
            await NearbyMultipeer.startAdvertising({
                strategy: STRATEGY,
                serviceId: SERVICE_ID,
                name: this.myEndpointName
            });
            console.log('MeshService: Advertising started as', this.myEndpointName);
        } catch (err) {
            console.error('MeshService: Start Advertising failed', err);
        }
    }

    async startDiscovery() {
        try {
            await NearbyMultipeer.startDiscovery({
                strategy: STRATEGY,
                serviceId: SERVICE_ID
            });
            console.log('MeshService: Discovery started');
        } catch (err) {
            console.error('MeshService: Start Discovery failed', err);
        }
    }

    async stopAll() {
        await NearbyMultipeer.stopAdvertising();
        await NearbyMultipeer.stopDiscovery();
        await NearbyMultipeer.stopAllEndpoints();
        this.peers.clear();
        this.connectedEndpoints.clear();
        this._notifyPeers();
    }

    async connect(endpointId) {
        try {
            await NearbyMultipeer.connect({
                displayName: this.myEndpointName,
                endpointId: endpointId
            });
            // Update status to 'connecting'
            const peer = this.peers.get(endpointId);
            if (peer) {
                peer.status = 'connecting';
                this.peers.set(endpointId, peer);
                this._notifyPeers();
            }
        } catch (err) {
            console.error('MeshService: Request Connection failed', err);
        }
    }

    async sendMessage(text) {
        if (this.connectedEndpoints.size === 0) return Promise.reject("No peers connected");

        const bytes = btoa(text); // Simple Base64 encoding for prototype
        try {
            // Send to ALL connected endpoints (Mesh-like broadcast)
            const targets = Array.from(this.connectedEndpoints);

            if (targets.length === 0) {
                console.warn("MeshService: No targets to send to");
                return false;
            }

            const sendPromises = targets.map(targetId =>
                NearbyMultipeer.sendMessage({
                    endpointId: targetId,
                    data: bytes
                }).catch(err => {
                    console.warn(`MeshService: Failed to send to ${targetId}`, err);
                    // Return failure info rather than throwing
                    return { error: err };
                })
            );

            // Use allSettled logic (implicitly handled above by catch) 
            // but Promise.all is fine now that we catch individual errors.
            await Promise.all(sendPromises);

            // Add to local log
            this._addMessage({
                id: Date.now(),
                sender: 'Me',
                text: text,
                timestamp: new Date().toISOString(),
                isMe: true
            });
            return true;
        } catch (err) {
            console.error('MeshService: Broadcast failed logic', err);
            // Don't throw, just log. We want the app to stay alive.
            return false;
        }
    }

    _handleIncomingMessage(endpointId, text) {
        const peer = this.peers.get(endpointId);
        const name = peer ? peer.endpointName : endpointId.substring(0, 5);

        this._addMessage({
            id: Date.now(),
            sender: name,
            text: text,
            timestamp: new Date().toISOString(),
            isMe: false
        });
    }

    _addMessage(msg) {
        this.messages = [...this.messages, msg];
        if (this.onMessageReceived) this.onMessageReceived(this.messages);
    }

    _notifyPeers() {
        if (this.onPeersUpdated) {
            this.onPeersUpdated(Array.from(this.peers.values()));
        }
    }

    subscribePeers(cb) {
        this.onPeersUpdated = cb;
        // Immediately invoke with current state so UI doesn't wait for next event
        if (cb && this.peers.size > 0) {
            const list = Array.from(this.peers.values());
            cb(list);
        }
        return () => { this.onPeersUpdated = null; };
    }

    subscribeMessages(cb) {
        this.onMessageReceived = cb;
        return () => { this.onMessageReceived = null; };
    }
}

export const meshService = new MeshService();
